"""
Phase 2D — Execution Errors
Standardized error codes and exception class for safe autonomous execution orchestration.
"""
from __future__ import annotations

# Standardized Error Codes
EXECUTION_NOT_FOUND = "EXECUTION_NOT_FOUND"
PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
WORKSPACE_NOT_AUTHORIZED = "WORKSPACE_NOT_AUTHORIZED"
INVALID_EXECUTION_STATE = "INVALID_EXECUTION_STATE"
INVALID_TASK_ID = "INVALID_TASK_ID"
INVALID_PERMISSION_LEVEL = "INVALID_PERMISSION_LEVEL"
BLOCKED_REQUIRES_PERMISSION = "BLOCKED_REQUIRES_PERMISSION"
FORBIDDEN_PERMISSION_LEVEL = "FORBIDDEN_PERMISSION_LEVEL"
DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY"
RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
EXECUTION_PAUSED = "EXECUTION_PAUSED"
EXECUTION_FAILED = "EXECUTION_FAILED"
NON_RETRYABLE_ERROR = "NON_RETRYABLE_ERROR"
TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
INVALID_REQUEST = "INVALID_REQUEST"
SENSITIVE_FILE = "SENSITIVE_FILE"
PATH_OUTSIDE_WORKSPACE = "PATH_OUTSIDE_WORKSPACE"

# Explicitly Non-Retryable Error Codes
NON_RETRYABLE_CODES = frozenset([
    "PERMISSION_DENIED",
    "SENSITIVE_FILE",
    "PATH_OUTSIDE_WORKSPACE",
    "WORKSPACE_NOT_AUTHORIZED",
    "INVALID_ARGUMENTS",
    "TOOL_NOT_REGISTERED",
    "BLOCKED_REQUIRES_PERMISSION",
    "FORBIDDEN_PERMISSION_LEVEL",
    "INVALID_PERMISSION_LEVEL",
    "INVALID_TASK_ID",
    "CIRCULAR_DEPENDENCY",
])


class ExecutionError(Exception):
    """Structured exception for execution engine errors."""
    def __init__(self, code: str, detail: str):
        super().__init__(detail)
        self.code = code
        self.detail = detail
