"""
Phase 2E — Modification Error Codes & Exception
Standardized error codes and structured exception class for code modification and patching.
"""
from __future__ import annotations

# Standardized Error Codes
MODIFICATION_NOT_FOUND     = "MODIFICATION_NOT_FOUND"
PROPOSAL_NOT_FOUND         = "PROPOSAL_NOT_FOUND"
AUTHORIZATION_NOT_FOUND    = "AUTHORIZATION_NOT_FOUND"
AUTHORIZATION_EXPIRED      = "AUTHORIZATION_EXPIRED"
AUTHORIZATION_CONSUMED     = "AUTHORIZATION_CONSUMED"
AUTHORIZATION_REVOKED      = "AUTHORIZATION_REVOKED"
WORKSPACE_NOT_AUTHORIZED   = "WORKSPACE_NOT_AUTHORIZED"
PLAN_NOT_FOUND             = "PLAN_NOT_FOUND"
EXECUTION_NOT_FOUND        = "EXECUTION_NOT_FOUND"
TASK_NOT_FOUND             = "TASK_NOT_FOUND"
INVALID_PATCH_SYNTAX       = "INVALID_PATCH_SYNTAX"
EMPTY_PATCH                = "EMPTY_PATCH"
PATH_OUTSIDE_WORKSPACE     = "PATH_OUTSIDE_WORKSPACE"
ABSOLUTE_PATH_REJECTED     = "ABSOLUTE_PATH_REJECTED"
SENSITIVE_FILE             = "SENSITIVE_FILE"
BLOCKED_SENSITIVE_CONTENT  = "BLOCKED_SENSITIVE_CONTENT"
BINARY_FILE_BLOCKED        = "BINARY_FILE_BLOCKED"
GENERATED_PATH_BLOCKED     = "GENERATED_PATH_BLOCKED"
FILE_STATE_CHANGED         = "FILE_STATE_CHANGED"
FILE_ALREADY_EXISTS        = "FILE_ALREADY_EXISTS"
FILE_NOT_FOUND             = "FILE_NOT_FOUND"
RESOURCE_LIMIT             = "RESOURCE_LIMIT"
BLOCKED_REQUIRES_PERMISSION = "BLOCKED_REQUIRES_PERMISSION"
PERMISSION_DENIED          = "PERMISSION_DENIED"
FORBIDDEN_PERMISSION_LEVEL = "FORBIDDEN_PERMISSION_LEVEL"
ROLLBACK_CONFLICT          = "ROLLBACK_CONFLICT"
ROLLBACK_FAILED            = "ROLLBACK_FAILED"
MODIFICATION_FAILED        = "MODIFICATION_FAILED"
MODIFICATION_LOCKED        = "MODIFICATION_LOCKED"
INVALID_REQUEST            = "INVALID_REQUEST"


class ModificationError(Exception):
    """Structured exception for modification, patch, and write engine errors."""
    def __init__(self, code: str, detail: str):
        super().__init__(detail)
        self.code = code
        self.detail = detail
