# Standardized Safe Errors for Tool Execution

WORKSPACE_NOT_AUTHORIZED = "WORKSPACE_NOT_AUTHORIZED"
PATH_OUTSIDE_WORKSPACE = "PATH_OUTSIDE_WORKSPACE"
TOOL_NOT_REGISTERED = "TOOL_NOT_REGISTERED"
PERMISSION_DENIED = "PERMISSION_DENIED"
SENSITIVE_FILE = "SENSITIVE_FILE"
RESOURCE_LIMIT = "RESOURCE_LIMIT"
INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
